/*
 * Created on 5 oct. 2013 ( Time 18:01:34 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.model.bean;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Persistent class for entity stored in table "ADHERENT"
 *
 * @author Telosys Tools Generator
 *
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="ADHERENT", schema="APP" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="Adherent.query1", query="SELECT x FROM Adherent x WHERE  " ),
//  @NamedQuery ( name="Adherent.query2", query="SELECT x FROM Adherent x WHERE  " )
// } )
public class Adherent implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="AD_ID", nullable=false)
    private int        adId         ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="AD_LOGIN", nullable=false, length=255)
    private String     adLogin      ;

    @Column(name="AD_PASSWORD", nullable=false, length=255)
    private String     adPassword   ;

    @Column(name="AD_NOM", nullable=false, length=255)
    private String     adNom        ;

    @Column(name="AD_PRENOM", nullable=false, length=255)
    private String     adPrenom     ;

    @Column(name="AD_ADRESSE", length=255)
    private String     adAdresse    ;

    @Column(name="AD_CODEPOSTAL", length=255)
    private String     adCodepostal ;

    @Column(name="AD_VILLE", length=255)
    private String     adVille      ;

	// "adPaId" (column "AD_PA_ID") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="AD_PA_ID", referencedColumnName="PA_ID", insertable=false, updatable=false)
    private Pays       pays        ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Adherent()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setAdId( int adId )
    {
        this.adId = adId ;
    }
    public int getAdId()
    {
        return this.adId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : AD_LOGIN ( VARCHAR ) 
    public void setAdLogin( String adLogin )
    {
        this.adLogin = adLogin;
    }
    public String getAdLogin()
    {
        return this.adLogin;
    }

    //--- DATABASE MAPPING : AD_PASSWORD ( VARCHAR ) 
    public void setAdPassword( String adPassword )
    {
        this.adPassword = adPassword;
    }
    public String getAdPassword()
    {
        return this.adPassword;
    }

    //--- DATABASE MAPPING : AD_NOM ( VARCHAR ) 
    public void setAdNom( String adNom )
    {
        this.adNom = adNom;
    }
    public String getAdNom()
    {
        return this.adNom;
    }

    //--- DATABASE MAPPING : AD_PRENOM ( VARCHAR ) 
    public void setAdPrenom( String adPrenom )
    {
        this.adPrenom = adPrenom;
    }
    public String getAdPrenom()
    {
        return this.adPrenom;
    }

    //--- DATABASE MAPPING : AD_ADRESSE ( VARCHAR ) 
    public void setAdAdresse( String adAdresse )
    {
        this.adAdresse = adAdresse;
    }
    public String getAdAdresse()
    {
        return this.adAdresse;
    }

    //--- DATABASE MAPPING : AD_CODEPOSTAL ( VARCHAR ) 
    public void setAdCodepostal( String adCodepostal )
    {
        this.adCodepostal = adCodepostal;
    }
    public String getAdCodepostal()
    {
        return this.adCodepostal;
    }

    //--- DATABASE MAPPING : AD_VILLE ( VARCHAR ) 
    public void setAdVille( String adVille )
    {
        this.adVille = adVille;
    }
    public String getAdVille()
    {
        return this.adVille;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setPays( Pays pays )
    {
        this.pays = pays;
    }
    public Pays getPays()
    {
        return this.pays;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(adId); 
        sb.append("|"); 
        sb.append(adLogin); 
        sb.append( "|" ); 
        sb.append(adPassword); 
        sb.append( "|" ); 
        sb.append(adNom); 
        sb.append( "|" ); 
        sb.append(adPrenom); 
        sb.append( "|" ); 
        sb.append(adAdresse); 
        sb.append( "|" ); 
        sb.append(adCodepostal); 
        sb.append( "|" ); 
        sb.append(adVille); 
        return sb.toString(); 
    }

}
