/*
 * Created on 5 oct. 2013 ( Time 18:01:35 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.model.bean;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import java.util.List;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Persistent class for entity stored in table "PAYS"
 *
 * @author Telosys Tools Generator
 *
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="PAYS", schema="APP" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="Pays.query1", query="SELECT x FROM Pays x WHERE  " ),
//  @NamedQuery ( name="Pays.query2", query="SELECT x FROM Pays x WHERE  " )
// } )
public class Pays implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="PA_ID", nullable=false)
    private int        paId         ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="PA_CODE", nullable=false, length=255)
    private String     paCode       ;

    @Column(name="PA_NOM", nullable=false, length=255)
    private String     paNom        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="pays", targetEntity=Adherent.class)
    private List<Adherent> listOfAdherent;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Pays()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPaId( int paId )
    {
        this.paId = paId ;
    }
    public int getPaId()
    {
        return this.paId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : PA_CODE ( VARCHAR ) 
    public void setPaCode( String paCode )
    {
        this.paCode = paCode;
    }
    public String getPaCode()
    {
        return this.paCode;
    }

    //--- DATABASE MAPPING : PA_NOM ( VARCHAR ) 
    public void setPaNom( String paNom )
    {
        this.paNom = paNom;
    }
    public String getPaNom()
    {
        return this.paNom;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    @XmlTransient
    public void setListOfAdherent( List<Adherent> listOfAdherent )
    {
        this.listOfAdherent = listOfAdherent;
    }
    public List<Adherent> getListOfAdherent()
    {
        return this.listOfAdherent;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(paId); 
        sb.append("|"); 
        sb.append(paCode); 
        sb.append( "|" ); 
        sb.append(paNom); 
        return sb.toString(); 
    }

}
