/*
 * Created on 7 oct. 2013 ( Time 08:51:44 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package com.model.persistence.services.jpa;

import com.model.bean.Adherent ;
import com.model.persistence.commons.jpa.GenericJpaService;
import com.model.persistence.services.AdherentPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Adherent" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class AdherentPersistenceJPA extends GenericJpaService<Adherent, Integer> implements AdherentPersistence {

	/**
	 * Constructor
	 */
	public AdherentPersistenceJPA() {
		super(Adherent.class);
	}

	public Adherent load( int adId ) {
		return super.load( adId );
	}

	public boolean delete( int adId ) {
		return super.delete( adId );
	}

	public boolean delete(Adherent entity) {
		if ( entity != null ) {
			return super.delete( entity.getAdId() );
		}
		return false ;
	}

}
