/*
 * Created on 7 oct. 2013 ( Time 08:51:45 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package com.model.persistence.services.jpa;

import com.model.bean.Article ;
import com.model.persistence.commons.jpa.GenericJpaService;
import com.model.persistence.services.ArticlePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Article" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ArticlePersistenceJPA extends GenericJpaService<Article, Integer> implements ArticlePersistence {

	/**
	 * Constructor
	 */
	public ArticlePersistenceJPA() {
		super(Article.class);
	}

	public Article load( int arId ) {
		return super.load( arId );
	}

	public boolean delete( int arId ) {
		return super.delete( arId );
	}

	public boolean delete(Article entity) {
		if ( entity != null ) {
			return super.delete( entity.getArId() );
		}
		return false ;
	}

}
