
/*
 * Created on 3 oct. 2013 ( Time 15:16:11 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.modele.mock;

import java.util.LinkedList;
import java.util.List;

import com.modele.bean.Pays;
import com.modele.mock.tool.MockValues;

public class PaysMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Pays createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Pays createInstance( int paId ) {
		Pays entity = new Pays();
		// Init Primary Key fields
		entity.setPaId( paId) ;
		// Init Data fields
		entity.setPaCode( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setPaNom( mockValues.nextString(255) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfAdherent( TODO ) ; // List<Adherent> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Pays> createList(int count) {
		List<Pays> list = new LinkedList<Pays>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
