/*
 * Created on 7 oct. 2013 ( Time 08:51:45 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.model.persistence.services;

import java.util.List;
import java.util.Map;

import com.model.bean.Pays ;

/**
 * Basic persistence operations for entity "Pays"
 * 
 * This Bean has a basic Primary Key : int
 *
 * @author Telosys Tools Generator
 *
 */
public interface PaysPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param pays
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Pays pays) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param paId
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(int paId) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param pays
	 */
	public void insert(Pays pays) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param paId
	 * @return the entity loaded (or null if not found)
	 */
	public Pays load(int paId) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<Pays> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<Pays> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<Pays> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param pays
	 * @return
	 */
	public Pays save(Pays pays) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<Pays> search( Map<String, Object> criteria ) ;
}
