/*
 * Created on 3 oct. 2013 ( Time 15:16:11 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.modele.persistence.services;

import java.util.List;
import java.util.Map;

import com.modele.bean.Adherent;

/**
 * Basic persistence operations for entity "Adherent"
 * 
 * This Bean has a basic Primary Key : int
 *
 * @author Telosys Tools Generator
 *
 */
public interface AdherentPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param adherent
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Adherent adherent) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param adId
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(int adId) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param adherent
	 */
	public void insert(Adherent adherent) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param adId
	 * @return the entity loaded (or null if not found)
	 */
	public Adherent load(int adId) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<Adherent> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<Adherent> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<Adherent> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param adherent
	 * @return
	 */
	public Adherent save(Adherent adherent) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<Adherent> search( Map<String, Object> criteria ) ;
}
