/*
 * Created on 3 oct. 2013 ( Time 15:16:11 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package com.modele.persistence.services.jpa;

import com.modele.bean.Pays;
import com.modele.persistence.commons.jpa.GenericJpaService;
import com.modele.persistence.services.PaysPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Pays" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class PaysPersistenceJPA extends GenericJpaService<Pays, Integer> implements PaysPersistence {

	/**
	 * Constructor
	 */
	public PaysPersistenceJPA() {
		super(Pays.class);
	}

	public Pays load( int paId ) {
		return super.load( paId );
	}

	public boolean delete( int paId ) {
		return super.delete( paId );
	}

	public boolean delete(Pays entity) {
		if ( entity != null ) {
			return super.delete( entity.getPaId() );
		}
		return false ;
	}

}
